### ISSUE TITLE
Promises error

### ISSUE THREAD

**Issue by InfSpell** [austinksmith/Hamsters.js#57]
Thank you for the wonderful library.
For several days now I have been trying to try working with promises and getting an error ...
Help me please :)
__________________________________________________________
Windows 10
Node v10.14.0
Hamsters 5.1.1
_________________________________________________________
Code ->

const Worker = require('workerpool').Worker
const hamsters = require('hamsters.js')

hamsters.init({
  Worker: Worker
})

var params = {
  array: [1, 2, 3, 4, 5, 6, 7, 8],
  threads: 1,
  aggregate: true
 }

 var method = function() {
   for(var i = 0; i < params.array.length; i++) {
    rtn.data.push(Math.sqrt(params.array[i]))
   }
 }

 hamsters.promise(params, method)
 .then(function(results) {
  console.log(results)
 }).catch(function(error) {
  console.error(error)
 })
_______________________________________________
Or ->
hamsters.promise(params, function() {
  for (let i=0; i<params.array; i++) {
    rtn.data.push(params.array[i] * 2)
  }
})
.then( (results) => {
  console.log(results)
}).catch( (error) => {
  console.error(error)
});
__________________________________________________
Error ->
ReferenceError: scaffold is not defined    at F:\X-project-inf\node_modules\hamsters.js\build\hamsters.node.min.js:1:19131    at new Promise (<anonymous>)    at e.value [as promise] (F:\X-project-Inf\node_modules\hamsters.js\build\hamsters.node.min.js:1:19029)    at Object.<anonymous> (F:\X-project-Inf\src\test.js:16:10) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32)    at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3) at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)

**Comment by austinksmith** [comment]
Do me a favor and try changing your init call to 

```js
hamsters.init({
   Worker: Worker,
   reactNative: false
})
```

I'm in the process of working out the recently discovered bugs in 5.11 and this is going to be fixed in 5.1.2 release, if you continue to have issues try downgrading to version 5.0.0

**Comment by austinksmith** [comment]
Another note, it looks like you're using the WorkerPool library and Hamsters.js already includes a thread pool system so when it initializes and you call the library you'll be spawning N threads where N is equal to the logical cores on your system, or 4 if it can't detect that. Calling a function will pull from the pool and just use whatever thread(s) are available and not busy, I'd imagine that might cause some conflicts.

I would suggest using a library like this alongside Hamsters.js https://github.com/audreyt/node-webworker-threads 

That will allow you to give Hamsters.js a native worker object to spawn threads with and since the library includes thread pooling already you don't need to duplicate that.

**Comment by InfSpell** [comment]
Thanks for your reply and recommendations.
Before asking for help, I tried all the configurations - `hamsters.init`
`reactNative: false` - `node: true` ... and other :)
Tomorrow I'll try 5.0.0 and look forward to 5.1.2
Thanks again for the great library and it's not because I love hamsters ))))))

**Comment by austinksmith** [comment]
ok and it’s not named Hamsters because I like hamsters either it’s a personal meaning only known to me plus it’s catchy lol

**Comment by austinksmith** [comment]
So I started digging into the code and I dont think 5.0.0 is going to solve our problem either, from what I remember I was in the process of rewriting a lot of stuff and rushed out the last release trying to get it done sooner before my birthday and I see why promises wasn't working before and isn't working right now. Part of the optimizations I was doing was making sure more things were done at initialization instead of during execution so there would be lower latency between the time you invoke a function and the function is actually executed within a thread or threads. Those optimization need some refining to handle all use cases so for now I'd suggest just using ``` hamsters.run ``` callback version and wait for 5.1.2 to be finished.

**Comment by InfSpell** [comment]
Thanks, I'll wait

**Comment by austinksmith** [comment]
Do me a favor and give the current dev branch a try, I've fixed two issues already from 5.11 and i'm working through the rest right now.

**Comment by InfSpell** [comment]
Getting an error
```
const Worker = require('workerpool').Worker
// const Worker = require('webworker-threads').Worker
const hamsters = require('./Hamsters.js-dev/build/hamsters.node')

hamsters.init({
  Worker: Worker
})

function foo() {
  let params = {
    array: [0,1,2,3,4],
    threads: 1,
    aggregate: true
  }

  hamsters.run(params, function() {
      let arr = params.array
      arr.forEach(function(item) {
        rtn.data.push(item * 2)
      })
  }, function(results) {
    console.log(results)
  })
}

foo()

```
Error ->
```
Hamsters.js v5.1.1 Info: Preparing the hamster wheels & readying hamsters @ 1543955710492
Hamsters.js v5.1.1 Error: undefined @ 1543955710496
```

**Comment by InfSpell** [comment]
For the test I use the workerpool, webworker-threads on version 5.1.1 displays
```
Hamsters.js v5.1.1 Info: Preparing the hamster wheels & readying hamsters @ 1543956767399
e {
  debug: false,
  importScripts: null,
  memoize: false,
  persistence: true,
  legacy: false,
  browser: false,
  webWorker: false,
  node: true,
  reactNative: false,
  shell: false,
  transferrable: true,
  atomics: true,
  proxies: true,
  isIE: [Function: value],
  logicalThreads: 4,
  Worker: [Function: constructor],
  sharedWorker: null }
Hamsters.js v5.1.1 Info: 4 Logical Threads Detected,
Spawning 4 Hamsters @ 1543956767405
Hamsters.js v5.1.1 Info: 4 hamsters ready and awaiting instructions @ 1543956767406
```
and freezes....

**Comment by austinksmith** [comment]
Hmm so the worker pool stuff I can't verify, but I am working on figuring out the issue where you're getting undefined right now. So basically it's trying to do some verification on what environment we're running in , reactNative, Node, Web, Legacy etc. and after compilation the habitat variable that contains these values is just an empty object at execution time, I think it's because internally the library is using a promise and within the promise the object isn't accessible so I have to change a few things around and pass the object into the method directly which should get us past this issue.

**Comment by austinksmith** [comment]
The reason there's so much broken stuff is 5.11 / 5.1.2 is a major change from previous versions with the goal at reducing runtime latency as low as possible, everything is pre-computed to the greatest extent possible and only your logic should be parsed leaving the only overhead being communication between threads.

**Comment by austinksmith** [comment]
Hey do me a favor and give the dev branch version another try, I've worked through why the threads were not responding to messages and also resolved promise support. There are some other issues I'm working through right now but in my testing using Firefox and hamsters.web.js promises are working and it shouldn't time out

**Comment by InfSpell** [comment]
Yes it works Chrome 71
```
var params = {
  array: [1, 2, 3, 4],
  threads: 1,
  aggregate: true
 }

 var method = function() {
   for(var i = 0; i < params.array.length; i++) {
    rtn.data.push(params.array[i] * 2)
   }
 }

 hamsters.promise(params, method)
 .then(function(results) {
  console.log(results)
 }).catch(function(error) {
  console.error(error)
 })
```
Console ->
```
Hamsters.js v5.1.1 Info: Preparing the hamster wheels & readying hamsters @ 1544031318509
Hamsters.js v5.1.1 Info: 8 Logical Threads Detected, Spawning 8 Hamsters @ 1544031318510
Hamsters.js v5.1.1 Info: 8 hamsters ready and awaiting instructions @ 1544031318517
{data: Array(1)}data: Array(1)0: (4) [2, 4, 6, 8]length: 1__proto__: Array(0)__proto__: Object
```

**Comment by austinksmith** [comment]
Node should be working right now too btw, there's some other stuff i'm fixing up but it promises work everywhere right now
